### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by inner100p** [LogicAndTrick/sledge#289]
Crash at startup beta 2.0.7.2
Log:

> 
	Direct3D 11.1 is required. (Veldrid.VeldridException)
	   at Veldrid.D3D11.D3D11CommandList..ctor(D3D11GraphicsDevice gd, CommandListDescription& description)
	   at Veldrid.D3D11.D3D11ResourceFactory.CreateCommandList(CommandListDescription& description)
	   at Sledge.Rendering.Engine.Engine..ctor() in D:\Github\sledge\Sledge.Rendering\Engine\Engine.cs:line 49
	   at Sledge.Rendering.Engine.Engine..cctor() in D:\Github\sledge\Sledge.Rendering\Engine\Engine.cs:line 18
	The type initializer for 'Sledge.Rendering.Engine.Engine' threw an exception. (System.TypeInitializationException)
	   at Sledge.Rendering.Engine.Engine.get_Instance() in D:\Github\sledge\Sledge.Rendering\Engine\Engine.cs:line 18
	   at Sledge.BspEditor.Rendering.Overlay.OverlayManager.OnStartup() in D:\Github\sledge\Sledge.BspEditor.Rendering\Overlay\OverlayManager.cs:line 29
	   at Sledge.Shell.Bootstrapper.<>c.<Startup>b__10_1(IStartupHook h) in D:\Github\sledge\Sledge.Shell\Bootstrapper.cs:line 93
	   at Sledge.Shell.Bootstrapper.<Handle>d__8`1.MoveNext() in D:\Github\sledge\Sledge.Shell\Bootstrapper.cs:line 66

My system:
CPU: i5-2310
GPU: Radeon RX460 4GB, drivers date: Jan 31 2018 Adrenalin 18.2.1
RAM: 8GB
Windows 7 x64, .NET Framework 4.7.2

**Comment by JoelTroch** [comment]
Sorry for the long wait reply but it seems that your GPU (graphics card) doesn't support DirectX 11

**Comment by hogsy** [comment]
Pretty sure the RX460 does and can support up to DX12, so as far as I can tell his GPU isn't the problem.
